<a href="https://colab.research.google.com/github/fzanart/GHDomains/blob/main/Refactoring.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import os
import pandas as pd
from nltk import word_tokenize
from nltk.stem.snowball import SnowballStemmer
from nltk import download
ss = SnowballStemmer('english')
from spacy import load
from spacy.matcher import Matcher
from tqdm import tqdm
nlp = load("en_core_web_sm", exclude=["tok2vec", "tagger", "parser",'senter', "attribute_ruler", "lemmatizer", 'ner'])
# from google.colab import drive
# drive.mount('/content/drive/')
download('punkt')

[nltk_data] Downloading package punkt to /Users/francisco/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [4]:
import multiprocessing as mp
pool = mp.Pool(mp.cpu_count())
mp.cpu_count()

8

In [20]:
directory = '/content/drive/MyDrive/GHDomains/Downloaded_repos/'
local_directory = '/Volumes/GoogleDrive/My Drive/GHDomains/Downloaded_repos/'
directory = local_directory

In [9]:
word_list = ['refactor', 'restruct', 'clean', 'not used', 'unused', 'reformat', 'import', 'remove', 'replace', 'split', 'reorg', 'rename', 'move']

matcher = Matcher(nlp.vocab)

# Add patterns
patterns= [[{"LOWER": "refactor"}],
            [{"LOWER": "restruct"}],
            [{"LOWER": "clean"}],
            [{"LOWER": "not"},{"LOWER": "use"}],    # used      steam = use
            [{"LOWER": "unus"}],                    # unused    steam = unus
            [{"LOWER": "reformat"}],                ## steam = reform
            [{"LOWER": "import"}],
            [{"LOWER": "remov"}],                   # remove    steam = remov
            [{"LOWER": "replac"}],                  # replace   steam = replac
            [{"LOWER": "split"}],                   ## split     steam = splite / split
            [{"LOWER": "reorg"}],                   # reorg     steam = reorg
            [{"LOWER": "renam"}],                   # rename    steam = renam
            [{"LOWER": "move"}]]

matcher.add("refactoring_pattern", patterns)

In [10]:
def word_matcher(text):
    
    try:
        with nlp.disable_pipes():
        # Tokenize the commit sentence:
            text = word_tokenize(text)
        # apply steam technique
            text = ' '.join([ss.stem(word) for word in text])
        # select matching words
            text = nlp(text)
            words = matcher(text)
    except TypeError:
        return 0

    if len(words)>0:

        return 1

    else:

        return 0

In [23]:
matches = []
to_rescan = []

for filename in tqdm(os.listdir(directory)):
    if not filename.startswith('.'):
        try:
            aux_reader = pd.read_json(directory+filename)
            commits    = aux_reader['Messages:'].size
            match      = aux_reader['Messages:'].apply(word_matcher).sum()
            filename   = filename.replace(':', '/')
            filename   = filename.replace('.json', '')
            matches.extend([(filename, commits, match)])
        except:
            print('None commits found in: ', filename)
            filename   = filename.replace(':', '/')
            filename   = filename.replace('.json', '')
            to_rescan.extend([filename])


df = pd.DataFrame(matches, columns =['Name', 'Commits', 'Matches'])
df

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 442/442 [18:12<00:00,  2.47s/it]


Name  Commits  Matches
0                                   limetext/lime     1104      150
1                                     pypa/pipenv     7318      709
2                                 deezer/spleeter      477       70
3    fchollet/deep-learning-with-python-notebooks       42        3
4                 microsoft/Web-Dev-For-Beginners     1265       60
..                                            ...      ...      ...
436                          akullpp/awesome-java     1590      174
437                           puppeteer/puppeteer     2483      376
438                                alibaba/arthas     1716       93
439                 atlassian/react-beautiful-dnd      795       86
440                                   plotly/dash     5776      703

[441 rows x 3 columns]

In [25]:
# chi-squared test with similar proportions
from scipy.stats import chi2_contingency
from scipy.stats import chi2
import numpy as np

df_path = '/content/drive/MyDrive/GHDomains/Resources/new_popular_df_predicted.csv'
df_path = '/Volumes/GoogleDrive/My Drive/GHDomains/Resources/new_popular_df_predicted.csv'

new_popular_df = pd.read_csv(df_path, usecols=['Name','Predicted_labels'])
new_popular_df

Name              Predicted_labels
0                              vuejs/devtools  Web libraries and frameworks
1             futurice/android-best-practices                 Documentation
2             microsoft/Web-Dev-For-Beginners                 Documentation
3                      airbnb/react-sketchapp  Web libraries and frameworks
4                        eugeneyan/applied-ml                 Documentation
..                                        ...                           ...
436                          railsware/upterm                Software tools
437                              matryer/xbar                Software tools
438          thedaviddias/Front-End-Checklist                 Documentation
439  electronicarts/CnC_Remastered_Collection                 Documentation
440                        ageron/handson-ml2                 Documentation

[441 rows x 2 columns]

In [26]:
join_data = pd.merge(new_popular_df, df, on ='Name', how ='inner')
join_data['Non refactoring commits'] = join_data['Commits'] - join_data['Matches']

columns = ['Name','Domain','Total commits', 'Refactoring commits', 'Non refactoring commits']
join_data.columns = columns
join_data = join_data[['Name','Domain', 'Refactoring commits', 'Non refactoring commits','Total commits']]
join_data

Name                        Domain  \
0                              vuejs/devtools  Web libraries and frameworks   
1             futurice/android-best-practices                 Documentation   
2             microsoft/Web-Dev-For-Beginners                 Documentation   
3                      airbnb/react-sketchapp  Web libraries and frameworks   
4                        eugeneyan/applied-ml                 Documentation   
..                                        ...                           ...   
436                          railsware/upterm                Software tools   
437                              matryer/xbar                Software tools   
438          thedaviddias/Front-End-Checklist                 Documentation   
439  electronicarts/CnC_Remastered_Collection                 Documentation   
440                        ageron/handson-ml2                 Documentation   

     Refactoring commits  Non refactoring commits  Total commits  
0                    246                     1723           1969  
1                     31                      216            247  
2                     60                     1205           1265  
3                    123                      657            780  
4                     22                      377            399  
..                   ...                      ...            ...  
436                  446                     2552           2998  
437                   96                      935           1031  
438                   82                      612            694  
439                    1                       11             12  
440                  153                      752            905  

[441 rows x 5 columns]

In [27]:
df = join_data.groupby(['Domain']).sum()
df

Refactoring commits  \
Domain                                                  
Application & System software                   26944   
Documentation                                   14657   
Non-web libraries and frameworks                39691   
Software tools                                  95797   
Web libraries and frameworks                    40523   

                                  Non refactoring commits  Total commits  
Domain                                                                    
Application & System software                      221592         248536  
Documentation                                      171036         185693  
Non-web libraries and frameworks                   218165         257856  
Software tools                                     684964         780761  
Web libraries and frameworks                       280503         321026

In [28]:
domains = join_data['Domain'].unique()

for domain in domains:
    print(domain, ':')
    data1 = df.loc[domain]
    data2 = df.loc[domains[domains != domain]].sum()
    aux = np.column_stack((data1, data2))[:2].T
    print(aux)
    stat, p, dof, expected = chi2_contingency(aux)
    print('dof=%d' % dof)
    print(expected)
    # interpret test-statistic
    prob = 0.95
    critical = chi2.ppf(prob, dof)
    print('probability=%.3f, critical=%.3f, stat=%.3f' % (prob, critical, stat))
    if abs(stat) >= critical:
        print('Dependent (reject H0)')
    else:
        print('Independent (fail to reject H0)')
    # interpret p-value
    alpha = 1.0 - prob
    print('significance=%.3f, p=%.3f' % (alpha, p))
    if p <= alpha:
        print('Dependent (reject H0)')
    else:
        print('Independent (fail to reject H0)')
    print('=========================================')

Web libraries and frameworks :
[[  40523  280503]
 [ 177089 1295757]]
dof=1
[[  38943.19656698  282082.80343302]
 [ 178668.80343302 1294177.19656698]]
probability=0.950, critical=3.841, stat=88.776
Dependent (reject H0)
significance=0.050, p=0.000
Dependent (reject H0)
Documentation :
[[  14657  171036]
 [ 202955 1405224]]
dof=1
[[  22526.1474152  163166.8525848]
 [ 195085.8525848 1413093.1474152]]
probability=0.950, critical=3.841, stat=3489.265
Dependent (reject H0)
significance=0.050, p=0.000
Dependent (reject H0)
Software tools :
[[ 95797 684964]
 [121815 891296]]
dof=1
[[ 94712.97992945 686048.02007055]
 [122899.02007055 890211.97992945]]
probability=0.950, critical=3.841, stat=24.978
Dependent (reject H0)
significance=0.050, p=0.000
Dependent (reject H0)
Application & System software :
[[  26944  221592]
 [ 190668 1354668]]
dof=1
[[  30149.5402303  218386.4597697]
 [ 187462.4597697 1357873.5402303]]
probability=0.950, critical=3.841, stat=450.110
Dependent (reject H0)
significanc